name: prestashop_sxe

services:
  db:
    image: mariadb:10.6
    container_name: prestashop_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      DB_SERVER: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: ${PS_DOMAIN}
      PS_COUNTRY: "es"
      PS_LANGUAGE: "es"
      ADMIN_MAIL: ${ADMIN_MAIL}
      ADMIN_PASSWD: ${ADMIN_PASSWD}
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL : install4577

    networks:
      - prestashop_network

    volumes:
      - prestashop_data:/var/www/html

  phpmyadmin:
    image: phpmyadmin:5
    container_name: prestashop_phpmyadmin
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - prestashop_network

volumes:
  db_data:
  prestashop_data:

networks:
  prestashop_network: